image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

eslint:
  stage: test
  image: node:alpine
  script:
    - npm install && npm run lint

prettylint:
  stage: test
  image: node:alpine
  script:
    - npm install && npm run prettylint

package-audit:
  stage: test
  image: node:alpine
  script:
    - npm audit

test:
  stage: test
  image: node:alpine
  script:
    - npm install && npm run test
